### ISSUE TITLE
Excuse me, use the react - native 0.46.2 installation error

### ISSUE THREAD

**Issue by shaoting0730** [jeanregisser/react-native-popover#31]
打扰一下,使用react-native 0.46.2 安装报错,信息如下:
Excuse me, use the react - native 0.46.2 installation error, the information is as follows:
![2017-07-14 9 43 44](https://user-images.githubusercontent.com/14305431/28194751-f1c45c8c-6878-11e7-8b53-98d7c4594a85.png)

**Comment by aizigao** [comment]
同样的问题，大佬是怎么解决的

**Comment by yazhengwang** [comment]
@aizigao @pheromone npm install --save github:jeanregisser/react-native-popover#8a443d2699b404d55c324edc8536255150340789

**Comment by kkkelicheng** [comment]
no matches found: github:jeanregisser/react-native-popover#8a443d2699b404d55c324edc8536255150340789

**Comment by AwdHanPeng** [comment]
Thanks ！
